sobre_titulo: "Sobre Tarcísio Lima"
sobre_texto: "Versatilidade, carisma e energia definem Tarcísio Lima. O artista pernambucano leva aos palcos um repertório dinâmico..."
whatsapp: "5581992192237"
email: "contato@tarcisiolima.com.br"
instagram: "https://www.instagram.com/tarcisiolima_cantor/"
